"use strict";
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const {initPersistence,loadRooms,saveRoom,saveAllRooms,deleteRoom,cleanupExpired,getPersistenceMode}=require("./persistence");
const ROOT=__dirname, PORT=Number(process.env.PORT||3000), HOST=process.env.HOST||"0.0.0.0", rooms=new Map();
const mime={".html":"text/html; charset=utf-8",".js":"application/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".png":"image/png",".webp":"image/webp",".jpg":"image/jpeg",".jpeg":"image/jpeg",".svg":"image/svg+xml",".pdf":"application/pdf",".json":"application/json; charset=utf-8"};
function code(){let s="";const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";do{s=Array.from({length:5},()=>a[Math.floor(Math.random()*a.length)]).join("")}while(rooms.has(s));return s}
function token(){return crypto.randomBytes(18).toString("hex")}
function send(res,status,obj){const b=JSON.stringify(obj);res.writeHead(status,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(b)}
function body(req){return new Promise((ok,fail)=>{let d="";req.on("data",c=>{d+=c;if(d.length>3e6)req.destroy()});req.on("end",()=>{try{ok(d?JSON.parse(d):{})}catch(e){fail(e)}});req.on("error",fail)})}
function publicRoom(r){return {code:r.code,hostId:r.hostId,players:r.players.map(p=>({id:p.id,name:p.name,color:p.color})),started:!!r.snapshot,snapshot:r.snapshot,version:r.version,updatedAt:r.updatedAt}}
function auth(r,t){return r&&r.players.find(p=>p.token===t)}
function staticFile(req,res){let u=new URL(req.url,"http://x").pathname;if(u==="/")u="/index.html";if(u==="/assets/board/tabuleiro.webp"){res.writeHead(302,{"location":"https://raw.githubusercontent.com/GilTheOne548/banco-imobiliario-parau/cbdb0569794d20668ab98d2a2fa1f920f624d14a/assets/board/tabuleiro.webp","cache-control":"no-store"});return res.end()}const f=path.normalize(path.join(ROOT,u));if(!f.startsWith(ROOT))return res.writeHead(403).end();fs.stat(f,(e,st)=>{if(e||!st.isFile())return res.writeHead(404).end("Não encontrado");res.writeHead(200,{"content-type":mime[path.extname(f).toLowerCase()]||"application/octet-stream","cache-control":u.startsWith("/assets/")?"public, max-age=86400":"no-cache"});fs.createReadStream(f).pipe(res)})}
async function persist(r){r.updatedAt=Date.now();await saveRoom(r);await saveAllRooms(rooms)}

const server=http.createServer(async(req,res)=>{try{
  const url=new URL(req.url,"http://localhost");
  if(req.method==="GET"&&url.pathname==="/health") return send(res,200,{ok:true,persistence:getPersistenceMode(),rooms:rooms.size});
  if(req.method==="POST"&&url.pathname==="/api/create"){const b=await body(req),name=String(b.name||"").trim().slice(0,18);if(!name)return send(res,400,{error:"Informe seu nome."});const c=code(),id=crypto.randomUUID(),t=token();const r={code:c,hostId:id,players:[{id,name,token:t,color:0}],snapshot:null,version:0,updatedAt:Date.now()};rooms.set(c,r);await persist(r);return send(res,200,{room:publicRoom(r),token:t,playerId:id,host:true})}
  if(req.method==="POST"&&url.pathname==="/api/join"){const b=await body(req),c=String(b.code||"").toUpperCase().trim(),name=String(b.name||"").trim().slice(0,18),r=rooms.get(c);if(!r)return send(res,404,{error:"Sala não encontrada."});if(r.snapshot)return send(res,409,{error:"A partida já começou."});if(r.players.length>=6)return send(res,409,{error:"A sala já tem 6 jogadores."});if(!name)return send(res,400,{error:"Informe seu nome."});const id=crypto.randomUUID(),t=token();r.players.push({id,name,token:t,color:r.players.length});r.version++;await persist(r);return send(res,200,{room:publicRoom(r),token:t,playerId:id,host:false})}
  if(req.method==="GET"&&url.pathname.startsWith("/api/room/")){const c=url.pathname.split("/").pop().toUpperCase(),r=rooms.get(c),p=auth(r,url.searchParams.get("token"));if(!r||!p)return send(res,404,{error:"Sala ou acesso inválido."});return send(res,200,{room:publicRoom(r),playerId:p.id,host:p.id===r.hostId})}
  if(req.method==="POST"&&url.pathname==="/api/start"){const b=await body(req),r=rooms.get(String(b.code||"").toUpperCase()),p=auth(r,b.token);if(!r||!p||p.id!==r.hostId)return send(res,403,{error:"Somente o anfitrião pode iniciar."});if(r.players.length<2)return send(res,409,{error:"São necessários pelo menos 2 jogadores."});if(r.snapshot)return send(res,409,{error:"A partida já começou."});r.snapshot=b.snapshot;r.version++;await persist(r);return send(res,200,{room:publicRoom(r)})}
  if(req.method==="POST"&&url.pathname==="/api/state"){const b=await body(req),r=rooms.get(String(b.code||"").toUpperCase()),p=auth(r,b.token);if(!r||!p||!r.snapshot)return send(res,403,{error:"Sala inválida."});if(Number(b.baseVersion)!==r.version)return send(res,409,{error:"Estado desatualizado.",room:publicRoom(r)});const current=r.snapshot.players&&r.snapshot.players[r.snapshot.current];if(!current||current.onlineId!==p.id)return send(res,403,{error:"Não é a sua vez."});r.snapshot=b.snapshot;r.version++;await persist(r);return send(res,200,{room:publicRoom(r)})}
  if(req.method==="POST"&&url.pathname==="/api/reset"){const b=await body(req),r=rooms.get(String(b.code||"").toUpperCase()),p=auth(r,b.token);if(!r||!p||p.id!==r.hostId)return send(res,403,{error:"Somente o anfitrião pode reiniciar."});r.snapshot=null;r.version++;await persist(r);return send(res,200,{room:publicRoom(r)})}
  if(req.method==="POST"&&url.pathname==="/api/leave"){const b=await body(req),r=rooms.get(String(b.code||"").toUpperCase()),p=auth(r,b.token);if(!r||!p)return send(res,404,{error:"Sala inválida."});if(r.snapshot)return send(res,409,{error:"Não é possível sair removendo o jogador depois que a partida começou."});r.players=r.players.filter(x=>x.id!==p.id);if(!r.players.length){rooms.delete(r.code);await deleteRoom(r.code);await saveAllRooms(rooms);return send(res,200,{deleted:true})}if(r.hostId===p.id)r.hostId=r.players[0].id;r.players.forEach((x,i)=>x.color=i);r.version++;await persist(r);return send(res,200,{room:publicRoom(r)})}
  return staticFile(req,res)
}catch(e){console.error(e);send(res,500,{error:"Erro interno",detail:process.env.NODE_ENV==="production"?undefined:String(e.message||e)})}});

(async()=>{try{await initPersistence();for(const r of await loadRooms())if(r&&r.code)rooms.set(r.code,r);console.log(`Persistência: ${getPersistenceMode()} | ${rooms.size} sala(s) restaurada(s)`);server.listen(PORT,HOST,()=>console.log(`Banco Imobiliário de Paraú ativo na porta ${PORT}`))}catch(e){console.error("Falha ao iniciar persistência:",e);process.exit(1)}})();
setInterval(async()=>{const now=Date.now();for(const[c,r]of rooms){if(now-r.updatedAt>7*24*60*60*1000){rooms.delete(c);try{await deleteRoom(c)}catch(e){console.warn(e.message)}}}try{await cleanupExpired(7);await saveAllRooms(rooms)}catch(e){console.warn("Falha na limpeza:",e.message)}},60*60*1000).unref();
