'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),E=require('../game-engine');
const data=require('../game-data.json');
function freshGame(){return E.fresh({players:[{id:'a',name:'Ana'},{id:'b',name:'Bruno'},{id:'c',name:'Carla'}]})}
function game(){const s=freshGame();s.initiative.complete=true;s.initiative.winner=0;return s}
test('cada jogador lança os dados e o maior resultado começa',()=>{const s=freshGame();assert.throws(()=>E.action(s,0,{action:'roll'}));let rounds=0;while(!s.initiative.complete){assert.ok(rounds++<50);for(const i of [...s.initiative.eligible])if(s.initiative.rolls[i]===undefined)E.action(s,i,{action:'initiative_roll'})}assert.equal(s.current,s.initiative.winner);assert.ok(s.players[s.current]);assert.throws(()=>E.action(s,s.current,{action:'initiative_roll'}));E.action(s,s.current,{action:'roll'});assert.equal(s.rolled,true)});
test('modo solo define o único jogador como inicial e permite testar turnos',()=>{const s=E.fresh({players:[{id:'solo',name:'Teste Solo'}]});E.action(s,0,{action:'initiative_roll'});assert.equal(s.initiative.complete,true);assert.equal(s.current,0);E.action(s,0,{action:'roll'});assert.equal(s.rolled,true);while(s.choices.length){const c=s.choices[0];E.action(s,c.player,{action:'choice',choiceId:c.id,value:c.options[0].value})}E.action(s,0,{action:'end'});assert.equal(s.current,0);assert.equal(s.turnNumber,2)});
test('personagem escolhido é preservado e a casa 8 é Taxa Municipal',()=>{const s=E.fresh({players:[{id:'a',name:'Ana',character:7}]});assert.equal(s.players[0].character,7);assert.equal(data.names[8],'Taxa Municipal');assert.equal(E.cardNames[9],'Financiamento')});
test('jogador pode sair e a partida continua com índices e posses consistentes',()=>{const s=game();s.current=1;s.rolled=true;s.titles={1:{owner:0,h:0},2:{owner:1,h:2},3:{owner:2,h:1}};E.action(s,0,{action:'offer',to:1,give:[1],take:[2],cash:0});E.removePlayer(s,1);assert.deepEqual(s.players.map(p=>p.name),['Ana','Carla']);assert.equal(s.current,1);assert.equal(s.rolled,false);assert.equal(s.titles[2],undefined);assert.equal(s.titles[3].owner,1);assert.equal(s.trades[0].status,'cancelled');E.action(s,1,{action:'roll'});assert.equal(s.rolled,true)});
test('negociação é atômica, consensual e preserva melhorias',()=>{const s=game();s.titles={1:{owner:0,h:2},3:{owner:1,h:1}};E.action(s,0,{action:'offer',to:1,give:[1],take:[3],cash:100000});const id=s.trades[0].id;assert.equal(s.titles[1].owner,0);assert.throws(()=>E.action(s,2,{action:'accept',tradeId:id}));E.action(s,1,{action:'accept',tradeId:id});assert.equal(s.titles[1].owner,1);assert.equal(s.titles[1].h,2);assert.equal(s.titles[3].owner,0);assert.equal(s.players[0].money,1400000);assert.equal(s.players[1].money,1600000);assert.throws(()=>E.action(s,1,{action:'accept',tradeId:id}))});
test('proposta revalida saldo e propriedade no aceite',()=>{const s=game();s.titles={1:{owner:0,h:0}};E.action(s,0,{action:'offer',to:1,give:[1],cash:-100000});s.players[1].money=0;assert.throws(()=>E.action(s,1,{action:'accept',tradeId:s.trades[0].id}));assert.equal(s.titles[1].owner,0);s.players[1].money=200000;s.titles[1].owner=2;assert.throws(()=>E.action(s,1,{action:'accept',tradeId:s.trades[0].id}));assert.equal(s.players[1].money,200000)});
test('dinheiro da negociação é arredondado para a nota de R$ 1.000 mais próxima',()=>{const s=game();s.titles={1:{owner:0,h:0},12:{owner:1,h:0}};E.action(s,0,{action:'offer',to:1,give:[1],take:[12],cash:1499});assert.equal(s.trades[0].cash,1000);E.action(s,0,{action:'offer',to:1,give:[1],take:[12],cash:1500});assert.equal(s.trades[1].cash,2000);E.action(s,0,{action:'offer',to:1,give:[1],take:[12],cash:-1500});assert.equal(s.trades[2].cash,-2000);E.action(s,0,{action:'offer',to:1,give:[1],take:[12],cash:499});assert.equal(s.trades[3].cash,0)});
test('construção fora da casa atual e investimento usam permissões e valores',()=>{const s=game();s.titles={1:{owner:0,h:0},2:{owner:0,h:0},4:{owner:0,h:0},3:{owner:0,h:0}};E.action(s,0,{action:'build',space:1});assert.equal(s.titles[1].h,1);assert.equal(s.players[0].money,1450000);E.action(s,0,{action:'build',space:3});assert.equal(s.players[0].money,1200000);assert.equal(E.rent(s,3,10),450000);assert.throws(()=>E.action(s,1,{action:'build',space:3}));s.titles[3].h=5;assert.throws(()=>E.action(s,0,{action:'build',space:3}));s.titles[2].mortgaged=true;assert.equal(E.buildable(s,0,1),false)});
test('30 cartas possuem efeito e todas as escolhas terminam',()=>{for(let n=0;n<30;n++){const s=game();s.titles={1:{owner:0,h:1},2:{owner:0,h:0},4:{owner:0,h:0},12:{owner:1,h:2},13:{owner:1,h:0},15:{owner:2,h:0}};E.draw(s,0,n);assert.equal(s.lastCard.index,n);let count=0;while(s.choices.length){assert.ok(count++<30,'loop card '+n);const c=s.choices[0];E.action(s,c.player,{action:'choice',choiceId:c.id,value:c.options[0].value})}assert.ok(s.players.every(p=>Number.isFinite(p.money)&&p.money>=0))}});
test('efeitos persistentes e escolha de outro jogador',()=>{const s=game();s.titles={1:{owner:0,h:0},12:{owner:1,h:0}};E.draw(s,0,3);const c=s.choices[0];assert.throws(()=>E.action(s,1,{action:'choice',choiceId:c.id,value:'1'}));assert.throws(()=>E.action(s,0,{action:'end'}));E.action(s,0,{action:'choice',choiceId:c.id,value:'1'});assert.equal(E.rent(s,1,7),12000);E.draw(s,0,24);assert.equal(s.choices.length,2);while(s.choices.length){const c=s.choices[0];E.action(s,c.player,{action:'choice',choiceId:c.id,value:c.options[0].value})}assert.equal(E.rent(s,1,7),0)});
test('auditoria trata hotel corretamente e estatização retira título',()=>{const s=game();s.titles={1:{owner:0,h:5},2:{owner:0,h:2}};E.draw(s,0,17);assert.equal(s.players[0].money,1275000);E.draw(s,0,27);assert.equal(s.titles[2],undefined);assert.equal(s.players[0].money,1350000)});
test('baralho sorteia 30 cartas sem repetição antes de reembaralhar',()=>{const s=game(),seen=new Set();for(let n=0;n<30;n++){E.draw(s,0);seen.add(s.lastCard.index);while(s.choices.length){const c=s.choices[0];E.action(s,c.player,{action:'choice',choiceId:c.id,value:c.options[0].value})}}assert.equal(seen.size,30);E.draw(s,0);assert.equal(s.deckPos,1)});
test('rodada e dados são controlados pelo servidor',()=>{const s=game();E.action(s,0,{action:'roll'});assert.ok(s.lastDice.every(d=>d>=1&&d<=6));assert.throws(()=>E.action(s,0,{action:'roll'}));while(s.choices.length){const c=s.choices[0];E.action(s,c.player,{action:'choice',choiceId:c.id,value:c.options[0].value})}E.action(s,0,{action:'end'});assert.equal(s.current,1);assert.equal(s.turnNumber,2);assert.throws(()=>E.action(s,0,{action:'roll'}))});
